function LSEx


% Lindenmayer_System_Explorer is designed to generate and/or modify 
% Lindenmayer systems (grammars). 
% 
% In this main GUI you will have two choices (via two buttons):
% 
% Lindenmayer Sytem Generator
%     Using the Generator you can generate predefined Lindenmayer systems 
%     (e.g. Fibonacci) or you can define your own rules to create grammars. 
% 
% Lindenmayer System Modifier
%     Using the Modifier you can change and modify existing L-systems, by 
%     building rules to iteratively replace chains of n characters of the 
%     system with chains of m other ones. 
%     
% See detailed description about the usage and the parameters in the 
% User Manual or by pressing the help button.
% 
% For help and support feel free to contact: l-s-ex@gmx.co.uk
% 
% Version 1.0 by Michael Lindner 
% University of Reading, 2017
% Center for Integrative Neuroscience and Neurodynamics
%
%
%
% Copyright (c) 2017, Michael Lindner and James Douglas Saddy
%
% All rights reserved.
%
% Redistribution and use in source and binary forms, with or without
% modification, are permitted provided that the following conditions are
% met:
%
%    * Redistributions of source code must retain the above copyright
%      notice, this list of conditions and the following disclaimer.
%    * Redistributions in binary form must reproduce the above copyright
%      notice, this list of conditions and the following disclaimer in
%      the documentation and/or other materials provided with the distribution
%
% THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
% AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
% IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
% ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
% LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
% CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
% SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
% INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
% CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
% ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
% POSSIBILITY OF SUCH DAMAGE.
%
% 

global hmenu name

name='LSEx';

BackgroundColor=[.7 .7 .7];
NameColor=[.5 1 .2];

cfg.figure_pos=calculate_figure_pos;

ver='1.0';

logo=imread('LSExm.png');
%logoy=size(logo,1);

hmenu=figure('Name', 'Lindenmayer System Explorer', ...
    'Visible', 'on', 'Units', 'pixels', ...
    'MenuBar', 'none', 'ToolBar', 'none', ...
    'Resize', 'off', 'NumberTitle', 'off',...
    'Position', cfg.figure_pos,...
    'Color',BackgroundColor);

uicontrol('units','pixels','position',[50 430 300 125],'cdata',logo)



uicontrol('Style','text', ...
    'HorizontalAlignment','center', ...
    'Position',[20,390,380,30], ...
    'FontSize',15,...
    'ForegroundColor',NameColor,...
    'String','Lindenmayer System Explorer',...
    'BackgroundColor',BackgroundColor);

uicontrol('Style','text', ...
    'HorizontalAlignment','left', ...
    'Position',[150,365,170,20], ...
    'FontSize',10,...
    'ForegroundColor',[0 0 0],...
    'String',['Version: ',ver],...
    'BackgroundColor',BackgroundColor);


uicontrol('Style','text', ...
    'HorizontalAlignment','center', ...
    'Position',[20,330,380,20], ...
    'FontSize',10,...
    'ForegroundColor',[0 0 0],...
    'String','by Michael Lindner and Doug Saddy',...
    'BackgroundColor',BackgroundColor);

uicontrol('Style','text', ...
    'HorizontalAlignment','center', ...
    'Position',[20,300,380,20], ...
    'FontSize',10,...
    'ForegroundColor',[0 0 0],...
    'String','University of Reading',...
    'BackgroundColor',BackgroundColor);
uicontrol('Style','text', ...
    'HorizontalAlignment','center', ...
    'Position',[20,260,380,40], ...
    'FontSize',10,...
    'ForegroundColor',[0 0 0],...
    'String','School of Psychology and Clinical Language Sciences &',...
    'BackgroundColor',BackgroundColor);
uicontrol('Style','text', ...
    'HorizontalAlignment','center', ...
    'Position',[20,230,380,40], ...
    'FontSize',10,...
    'ForegroundColor',[0 0 0],...
    'String','Center for Integrative Neuroscience and Neurodynamics',...
    'BackgroundColor',BackgroundColor);



% generate button
MENU.button_classic=uicontrol('Style', 'pushbutton', ...
    'String', 'Lindenmayer System Generator', ...
    'Units', 'pixels',...
    'Position', [10,140,380,80],...
    'Callback',@start_classic);

% generate button
MENU.button_n2n=uicontrol('Style', 'pushbutton', ...
    'String', 'Lindenmayer System Modifier', ...
    'Units', 'pixels',...
    'Position', [10,50,380,80],...
    'Callback',@start_n2n);


% about button - as pushbutton - bottom right
MENU.button_about=uicontrol('Style', 'pushbutton', ...
    'String', 'Help', ...
    'Units', 'pixels',...
    'Position', [150,20,100,20],...
    'Callback',@menu_about_function);


% quit button - as pushbutton - bottom right
MENU.button_quit=uicontrol('Style', 'pushbutton', ...
    'String', 'Quit', ...
    'Units', 'pixels',...
    'Position', [290,20,100,20],...
    'Callback',@menu_quit_function);



uicontrol('Style','text', ...
    'HorizontalAlignment','left', ...
    'Position',[1,3,390,10], ...
    'FontSize',6,...
    'ForegroundColor',[.55 .55 .55],...
    'String',['Lindenmayer System Explorer by Michael Lindner and Doug Saddy, University of Reading'],...
    'BackgroundColor',BackgroundColor);






    function start_classic(~,~)
       
         LSEx_gen
        
    end

    function start_n2n(~,~)
       
        LSEx_mod
        
    end


   function menu_about_function(~,~)

            about_text={'','',...
                'Lindenmayer System Explorer  ',...
                '','',...
                'This tool is designed to generate and/or modify Lindenmayer ',...
                'systems/grammars.',...
                'Using the Generator you can generate predefined',...
                'Lindenmayer systems (e.g. Fibonacci) or you can define your own',...
                'rules to create grammar.',...
                '',...
                'Using the Modifier you can change and modify existing L-systems,',...
                'by building rules to iteratively replace chains of n characters',...
                'of the system with chains of m other ones.',...
                '',...
                'Enjoy playing around with this tool!',...
                '',...
                'Copyright (c) 2017, Michael Lindner and James Douglas Saddy',...
                '',...
                'All rights reserved.',...
                '',...
                'Redistribution and use in source and binary forms, with or without',...
                'modification, are permitted provided that the following conditions are',...
                'met:',...
                '',...
                '   * Redistributions of source code must retain the above copyright',...
                '     notice, this list of conditions and the following disclaimer.',...
                '   * Redistributions in binary form must reproduce the above copyright',...
                '     notice, this list of conditions and the following disclaimer in',...
                '     the documentation and/or other materials provided with the distribution',...
                '',...
                'THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"',...
                'AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE',...
                'IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE',...
                'ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE',...
                'LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR',...
                'CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF',...
                'SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS',...
                'INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN',...
                'CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)',...
                'ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE',...
                'POSSIBILITY OF SUCH DAMAGE.',...
                '',...
                ['Version ',ver,' by Michael Lindner and Doug Saddy'],...
                'l-s-ex@gmx.co.uk',...
                'University of Reading, 2017',...
                'Center for Integrative Neuroscience and Neurodynamics',...
                'https://www.reading.ac.uk/cinn/cinn-home.aspx'};
            
            f=figure('menu','none','toolbar','none','name',...
                'Example script','NumberTitle','Off');
            hPan = uipanel(f,'Units','normalized');
            uicontrol(hPan, 'Style','listbox', ...
            'HorizontalAlignment','left', ...
            'Units','normalized', 'Position',[0 .2 1 .8], ...
            'String',about_text);

            
            btn=uicontrol('Style','pushbutton','String','Close',...
                'position',[10 10 200 20],...
                'Callback',@close_about);
                
            function close_about(hObject,callbackdata)
                close(f)
            end
        end


    function figure_pos=calculate_figure_pos
        % calculate figure position at ~ center of screen
        % get actual screen resolution
        screen_size=get(0,'Screensize');
        % lower left corner horizontal position
        figure_pos(1)=screen_size(3)/2-200;
        % lower left corner vertical position
        figure_pos(2)=screen_size(4)/2-200;
        % horizontal size of the GUI
        figure_pos(3)=400;
        % vertical size of the GUI
        figure_pos(4)=550;
    end

    function menu_quit_function(~,~)
        clear all
        clc
        close all
        fprintf(['\n',...
            '################################################\n',...
            '#                                              #\n',...
            '#           Thank you for using the            #\n',...
            '#                                              #\n',...
            '#         Lindenmayer System Explorer          #\n',...
            '#                                              #\n',...
            '#       Doug Saddy and Michael Lindner         #\n',...
            '#                                              #\n',...
            '################################################\n'])
        pause(3)
    end

    

end
